Manu
cruz636/bootcampy_2021 pull request #5
Opened 2021-05-25 16:00 UTC by tomasrom

2021-05-25 21:49 UTC, cruz636 requested changes

2021-05-25 21:49 UTC, cruz636 commented on 03_hangman/hangman.py
> +    index = random.randint(0,len(words))
whitespace after comma

2021-05-25 21:49 UTC, cruz636 commented on 03_hangman/hangman.py
> +        index = random.randint(0,len(words))
same above

2021-05-25 21:49 UTC, cruz636 commented on 03_hangman/hangman.py
> +word = get_word()
code must be inside a def

2021-05-25 21:49 UTC, cruz636 commented on 03_hangman/hangman.py
> +    #print(word)
remove line

2021-05-25 21:49 UTC, cruz636 commented on README.md
>  - [x] 2- Dictonary @cruz636
add @tomasrom at line 11 and 13

2021-05-25 23:28 UTC, tomasrom commented on 03_hangman/hangman.py
> +    index = random.randint(0,len(words))
done

2021-05-25 23:28 UTC, tomasrom commented on 03_hangman/hangman.py
> +        index = random.randint(0,len(words))
done

2021-05-25 23:29 UTC, tomasrom commented on 03_hangman/hangman.py
> +word = get_word()
done

2021-05-25 23:29 UTC, tomasrom commented on 03_hangman/hangman.py
> +    #print(word)
done

2021-05-25 23:29 UTC, tomasrom commented on README.md
>  - [x] 2- Dictonary @cruz636
done

2021-05-25 23:48 UTC, cruz636 commented
@tomasrom resolve conflics

2021-05-26 00:02 UTC, cruz636 approved these changes
LGTM!

2021-05-26 00:03 UTC, merged